# Main Configuration
theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Berlin

title: Karthik Jayadevan
tagline: Physics graduate

description: >-
  I'm passionate about physics, mathematics, didactics, and technology.

url: "https://profile.karthikjayd.com"

github:
  username: karthikjayd

social:
  name: Karthik Jayadevan
  email: hi@karthikjayd.com
  links:
    - https://github.com/karthikjayd

theme_mode: light

cdn: "https://chirpy-img.netlify.app"
avatar: "/commons/avatar.jpg"

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10
baseurl: ""

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
